import type { Metadata } from "next";
import Wp2shellClient from "./wp2shell-client";
import { SITE_URL, SITE_NAME } from "@/lib/site";

const slug = "wp2shell-wordpress-core-rce";
const url = `${SITE_URL}/blog/${slug}`;
// Representative content image for Article structured data. The social
// (og:image) card is still generated by the file-based opengraph-image route.
const articleImage = `${SITE_URL}/assets/wordpress-core/wordpress-core.webp`;

const title =
  "wp2shell WordPress RCE (CVE-2026-60137 & 63030) — Patch Guide";
const description =
  "wp2shell is a pre-auth RCE in WordPress core affecting 6.9.x and 7.0.x. Check if you're vulnerable, patch to 6.9.5 or 7.0.2, and see why core flaws hit every site at once.";

export const metadata: Metadata = {
  title,
  description,
  keywords: [
    "wp2shell",
    "CVE-2026-60137",
    "CVE-2026-63030",
    "WordPress RCE",
    "WordPress security",
    "pre-auth RCE",
    "WordPress 7.0.2",
    "WordPress 6.9.5",
    "WordPress core vulnerability 2026",
  ],
  alternates: { canonical: `/blog/${slug}` },
  openGraph: {
    title,
    description,
    url: `/blog/${slug}`,
    type: "article",
    publishedTime: "2026-07-22",
    modifiedTime: "2026-07-22",
    authors: [SITE_NAME],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
};

const articleJsonLd = {
  "@context": "https://schema.org",
  "@type": "TechArticle",
  headline:
    "wp2shell: The WordPress Core Flaw That Needs No Plugin, No Login, No Excuse",
  description,
  image: articleImage,
  datePublished: "2026-07-22",
  dateModified: "2026-07-22",
  author: {
    "@type": "Person",
    name: SITE_NAME,
    url: SITE_URL,
    jobTitle: "Full-Stack Web Developer",
    sameAs: [
      "https://github.com/Kendaichi",
      "https://ph.linkedin.com/in/franclloyd-dagdag",
    ],
  },
  publisher: { "@type": "Person", name: SITE_NAME, url: SITE_URL },
  mainEntityOfPage: { "@type": "WebPage", "@id": url },
  keywords:
    "wp2shell, CVE-2026-60137, CVE-2026-63030, WordPress RCE, WordPress security, pre-auth RCE, WordPress 7.0.2, WordPress 6.9.5",
  about: [
    { "@type": "Thing", name: "WordPress" },
    { "@type": "Thing", name: "Remote Code Execution" },
    { "@type": "Thing", name: "Web Application Security" },
  ],
  proficiencyLevel: "Intermediate",
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is wp2shell?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "wp2shell is the name given to a pre-authentication remote code execution chain in WordPress core, disclosed on July 17, 2026 by Searchlight Cyber's Assetnote team. It combines a SQL injection (CVE-2026-60137) with a REST API batch-route confusion bug (CVE-2026-63030) to let an anonymous attacker run code on the server.",
      },
    },
    {
      "@type": "Question",
      name: "Which WordPress versions are affected by wp2shell?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The full RCE chain affects WordPress 6.9.0 through 6.9.4 and 7.0.0 through 7.0.1. The SQL injection component alone also affects 6.8.0 through 6.8.5, but cannot be chained to remote code execution on that branch because the REST API batch endpoint did not exist yet.",
      },
    },
    {
      "@type": "Question",
      name: "Which WordPress version fixes wp2shell?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "WordPress 6.9.5 and 7.0.2 fix the full chain. The 6.8 branch received a separate fix for the SQL injection component.",
      },
    },
    {
      "@type": "Question",
      name: "Do I need plugins installed to be vulnerable to wp2shell?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. A stock WordPress install with zero plugins running an affected version is exploitable, because both flaws live in WordPress core.",
      },
    },
    {
      "@type": "Question",
      name: "Is wp2shell being exploited in the wild?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Public proof-of-concept exploits appeared on GitHub within a day of disclosure, and security firm watchTowr reported the first signs of in-the-wild exploitation shortly afterward.",
      },
    },
    {
      "@type": "Question",
      name: "Does a WAF protect me from wp2shell?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Only partially and temporarily. Cloudflare deployed WAF rules for both CVEs across all plans, including free accounts, but it stated these reduce exposure rather than replace patching. Update WordPress core as the actual fix.",
      },
    },
    {
      "@type": "Question",
      name: "How do I check if my WordPress site is vulnerable to wp2shell?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Check your version in the WordPress admin dashboard or run 'wp core version' via WP-CLI, then compare it against the affected version ranges. Searchlight Cyber also published a free checker at wp2shell.com.",
      },
    },
  ],
};

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` },
    { "@type": "ListItem", position: 2, name: "Blog", item: `${SITE_URL}/blog` },
    {
      "@type": "ListItem",
      position: 3,
      name: "wp2shell WordPress Core RCE",
      item: url,
    },
  ],
};

export default function Page() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <Wp2shellClient />
    </>
  );
}
